// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple API
 *
 * A simple API example
 *
 * API version: 1.0.0
 */

package openapi




type HelloGet200Response struct {

	Message string `json:"message,omitempty"`
}

// AssertHelloGet200ResponseRequired checks if the required fields are not zero-ed
func AssertHelloGet200ResponseRequired(obj HelloGet200Response) error {
	return nil
}

// AssertHelloGet200ResponseConstraints checks if the values respects the defined constraints
func AssertHelloGet200ResponseConstraints(obj HelloGet200Response) error {
	return nil
}
